-- noinspection SqlNoDataSourceInspectionForFile

INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2000-01-01', 'Italy', 'Como');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2001-02-02', 'Italy', 'Rome');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2002-03-03', 'Italy', 'Venice');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2003-04-04', 'Italy', 'Sicily');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2004-05-05', 'Italy', 'Florence');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2005-06-06', 'Germany', 'Berlin');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2006-07-07', 'Germany', 'Hamburg');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2007-08-08', 'Germany', 'Munich');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2008-09-09', 'Germany', 'Köln');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2009-10-10', 'Germany', 'Frankfurt');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2010-11-11', 'Germany', 'Stuttgart');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2011-12-12', 'Austria', 'Vienna');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2012-01-13', 'Austria', 'Graz');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2013-02-14', 'Austria', 'Linz');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2014-03-15', 'Austria', 'Salzburg');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2015-04-16', 'France', 'Paris');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2016-05-17', 'France', 'Marseille');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2017-06-18', 'France', 'Lyon');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2018-07-19', 'France', 'Toulouse');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2019-08-15', 'France', 'Nice');
INSERT INTO TRIP (TRIP_DATE, COUNTRY, PLACE) VALUES ('2020-09-16', 'France', 'Nantes');